### ISSUE TITLE
Facebook Simple Social Analytics error

### ISSUE THREAD

**Issue by kastony** [secrethash/trickster#2]
I get an 

ErrorException in Trickster.php line 208:
Undefined index: shares

I'm using laravel 5.3.19

**Comment by secrethash** [comment]
Fixed the bug. Thanks for lighting it up. I have changed the function a bit and deprecated twitter, read the Readme file for more info.

**Comment by secrethash** [comment]
https://github.com/secrethash/trickster#7-simple-social-analytics

**Comment by secrethash** [comment]
Update trickster using `composer update` command
