### ISSUE TITLE
Return analytic data as objects

### ISSUE THREAD

**Issue by m1guelpf** [secrethash/trickster#5]
I think object would make everything more easy:
```php
$fbShareCount = $fbAnalytics['share_count']
```
to
```php
$fbShareCount = $fbAnalytics->share_count
```
@secrethash What do you think? Adding it would be less than one line...

**Comment by secrethash** [comment]
Now returning shares and comments count as an object. See `v2.2.0` release notes.

**Comment by m1guelpf** [comment]
@secrethash Awesome!
